config/routes.rb
Rails.application.routes.draw do
  resources :product_to_trackers,:except => [:edit, :update, :show]
  resources :trackers, :except => [:new, :create, :edit, :update, :show, :destroy]
  resources :products, :except => [:new, :create, :edit, :update, :destroy]
  resources :comments
  devise_for :users
  resources :posts
  root 'home#home'
  get 'contact', to: 'home#contact'
  get 'products', to: 'products#index'
  get 'fourm', to: 'posts#index'
  get 'userposts', to: 'posts#display_user_posts'
  get 'tradingtracker', to: 'trackers#index'
  get 'about', to: 'about#index'
  get 'usercomments', to: 'comments#display_user_comments'
  post 'request_contact', to: 'home#request_contact'


end

app/controllers/home_controller.rb
class HomeController < ApplicationController

  def home
  end


  def contact
  end

  def request_contact #mailer form method
    name = params[:name]
    email = params[:email]
    telephone = params[:telephone]
    message = params[:message]
    ContactMailer.contact_email(email, name, telephone, message).deliver_now
    flash[:notice] = I18n.t('home.request_contact.email_sent')
    redirect_to root_path
  end

end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/contact.html.haml
%title= t('.title')
%body{:onload => "function()"}
  %h2=t('.title')
  %p=t('.contact_us')

  = form_tag request_contact_path,:id => 'ContactForm', method: 'post' do
    = label_tag :name, t('.name')
    = text_field_tag :name
    = label_tag :email, t('.email')
    = email_field_tag :email
    = label_tag :telephone, t('.telephone')
    = telephone_field_tag :telephone
    = label_tag :message, t('.message')
    = text_field_tag :message,'', size: 70
    = submit_tag t('.submit')

app/views/home/home.html.haml
%title= t('app_title')
%h3=t('.welcome')
%h3=t('.welcome2')
= javascript_include_tag 'home'
.alert
  %span.closebtn{:onclick => "this.parentElement.style.display='none';"} ×
  %strong WARNING!
  due to COVID-19 site moderation will be lower than usual. We hope you stick with us during these difficult times.




%div#incoming_content
  %body
    %h2= t('.game_title')
    %p= t('.game_description')

    .form
      %label{:for => "guessField"}
        =t('.box_text') + ":"
      %input#guessField.guessField{:type => "text"}/
      %input#submitguess.guessSubmit{:type => "submit", :value => "Submit guess"}/
      <button onClick="window.location.reload();">Play again</button>