config/routes.rb
Rails.application.routes.draw do
  resources :product_to_trackers,:except => [:edit, :update, :show]
  resources :trackers, :except => [:new, :create, :edit, :update, :show, :destroy]
  resources :products, :except => [:new, :create, :edit, :update, :destroy]
  resources :comments
  devise_for :users
  resources :posts
  root 'home#home'
  get 'contact', to: 'home#contact'
  get 'products', to: 'products#index'
  get 'fourm', to: 'posts#index'
  get 'userposts', to: 'posts#display_user_posts'
  get 'tradingtracker', to: 'trackers#index'
  get 'about', to: 'about#index'
  get 'usercomments', to: 'comments#display_user_comments'
  post 'request_contact', to: 'home#request_contact'


end

app/models/post.rb
class Post < ApplicationRecord
  validates_presence_of  :title,  :content,  :date,  :author
  has_many:comments, dependent: :destroy
  validates :title, uniqueness: true
  validates_length_of:title, maximum: 30
  validates_length_of:author, maximum: 20
  belongs_to  :user
  scope :user_posts, ->(user) { where(['user_id = ?', user.id]) } #scope method so user can only see their posts
  def self.search_by(search_term) #a model search to search by the search term inputted via the view sent via controller method
    where("LOWER(title) LIKE :search_term OR LOWER(author) LIKE :search_term OR LOWER(date) LIKE :search_term", search_term: "%#{search_term.downcase}")
  end #looks for matches within title, author and date
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user! # users must be logged in to access any post page
  # GET /posts
  # GET /posts.json
  def index
    @posts = Post.all
    if params[:search] #filters post by search term inputted by user
      @search_term = params[:search]
      @posts = @posts.search_by(@search_term)
    end
  end

  def display_user_posts
    @posts = Post.user_posts(current_user)
    if params[:search]#filters post by search term inputted by user
      @search_term = params[:search]
      @posts = @posts.search_by(@search_term).user_posts(current_user)
    end
  end

  # GET /posts/1
  # GET /posts/1.json
  def show
  end

  # GET /posts/new
  def new
    @post = Post.new
  end

  # GET /posts/1/edit
  def edit
    if @post.user != current_user #validating so only posts owner can edit it
      redirect_to posts_url, notice: t('.notice')
    else
    end
  end

  # POST /posts
  # POST /posts.json
  def create
    @post = Post.new(post_params)
    @post.user = current_user #when post is created a user is assigned to its user field
    respond_to do |format|
      if @post.save
        format.html { redirect_to @post, notice: t('.notice') }
        format.json { render :show, status: :created, location: @post }
      else
        format.html { render :new }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /posts/1
  # PATCH/PUT /posts/1.json
  def update
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to @post, notice: t('.notice') }
        format.json { render :show, status: :ok, location: @post }
      else
        format.html { render :edit }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1
  # DELETE /posts/1.json
  def destroy
    @post.destroy
    respond_to do |format|
      format.html { redirect_to posts_url, notice: t('.notice') }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @post = Post.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def post_params
      params.require(:post).permit(:title, :content, :author, :date)
    end
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/posts/_form.html.haml
= form_for @post do |f|
  - if @post.errors.any?
    #error_explanation
      %h2= "#{pluralize(@post.errors.count, "error")} prohibited this post from being saved:"
      %ul
        - @post.errors.full_messages.each do |message|
          %li= message

  .field
    = f.label :title
    = f.text_field :title
  .field
    = f.label :content
    = f.text_area :content
  .field
    = f.label :author
    = f.text_field :author
  .field
    = f.label :date
    = f.date_select :date
  .actions
    = f.submit t('save')

app/views/posts/display_user_posts.html.haml
%h2= t('.title')
%title= t('.title')
= form_for "",url: userposts_path, role: "search", method: :get do
  = text_field_tag :search, @search_term,placeholder: "Search..."
#striped2
  .striped
    %table{:style => "width:70%"}
      %thead
        %tr
          %th=t('.heading1')
          %th=t('.heading2')
          %th=t('.heading3')
          %th
          %th

          %tbody
            - @posts.each do |post|
              %tr
                %td= post.title
                %td= post.author
                %td= post.date
                %td= link_to t('show'), post
                %td= link_to t('edit'), edit_post_path(post)
                %td= link_to t('delete'), post, method: :delete, data: { confirm: t('delete_message') }
        %br

app/views/posts/edit.html.haml
%title= t('app_title')
%h1=t('.edit')

= render 'form'

= link_to t('show'), @post
\|
= link_to t('back'), posts_path

app/views/posts/index.html.haml
%h2= t('.title')
%h4= t('.description')
%title= t('.title')
= form_for "",url: posts_path, role: "search", method: :get do
  = text_field_tag :search, @search_term,placeholder: "Search..."

%table{:cellpadding => "0", :cellspacing => "0"}
#striped2
  .striped
    %table{:style => "width:100%"}

      %thead
        %tr
          %th= t('.heading1')
          %th= t('.heading2')
          %th= t('.heading3')
          %th
          %th
          %th

      %tbody
        - @posts.each do |post|
          %tr
            %td= post.title
            %td= post.author
            %td= post.date
            %td= link_to t('read'), post
            -if post.user == current_user
              %td= link_to  t('edit'), edit_post_path(post)
              %td= link_to t('delete'), post, method: :delete, data: { confirm: 'Are you sure?' }


    %br

    %h3= link_to t('.new'), new_post_path

app/views/posts/new.html.haml
%h1 New post

= render 'form'

= link_to t('back'), posts_path

app/views/posts/show.html.haml
%title= t('app_title')
%h2
  = @post.title
%p
  = @post.content
%p
  %b By:
  = @post.author
  =","
  = @post.date




%p
  = link_to t('.add_comment'), new_comment_path(post_id: @post)

\|
= link_to t('back'), posts_path()
%h3= t('.comments_title') + ":"
%table
  %tbody
  - @post.comments.each do |comment|
    %tr
      %td="PokeBen user: "
      %td &nbsp;
      %td= comment.user_id
      %td &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;&nbsp; &nbsp; &nbsp;
      %td= comment.message
      %td
      -if comment.user == current_user
        %td= link_to t('edit'), edit_comment_path(comment)
        %td= link_to t('delete'), comment, method: :delete, data: { confirm: 'Are you sure?' }