config/routes.rb
Rails.application.routes.draw do
  resources :product_to_trackers,:except => [:edit, :update, :show]
  resources :trackers, :except => [:new, :create, :edit, :update, :show, :destroy]
  resources :products, :except => [:new, :create, :edit, :update, :destroy]
  resources :comments
  devise_for :users
  resources :posts
  root 'home#home'
  get 'contact', to: 'home#contact'
  get 'products', to: 'products#index'
  get 'fourm', to: 'posts#index'
  get 'userposts', to: 'posts#display_user_posts'
  get 'tradingtracker', to: 'trackers#index'
  get 'about', to: 'about#index'
  get 'usercomments', to: 'comments#display_user_comments'
  post 'request_contact', to: 'home#request_contact'


end

app/models/tracker.rb
class Tracker < ApplicationRecord
  has_many :product_to_trackers, dependent: :destroy
end

app/controllers/trackers_controller.rb
class TrackersController < ApplicationController
  before_action :set_tracker, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!
  # GET /trackers
  # GET /trackers.json
  def index
    @trackers = Tracker.last
    if @trackers == nil #creates tracker if one doesn't already exist
      @trackers= Tracker.create()
    else
    end
  end

  # GET /trackers/1
  # GET /trackers/1.json
  def show
  end

  # GET /trackers/new
  def new
    @tracker = Tracker.new
  end

  # GET /trackers/1/edit
  def edit
  end

  # POST /trackers
  # POST /trackers.json
  def create
    @tracker = Tracker.new(tracker_params)

    respond_to do |format|
      if @tracker.save
        format.html { redirect_to @tracker, notice: t('.notice') }
        format.json { render :show, status: :created, location: @tracker }
      else
        format.html { render :new }
        format.json { render json: @tracker.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /trackers/1
  # PATCH/PUT /trackers/1.json
  def update
    respond_to do |format|
      if @tracker.update(tracker_params)
        format.html { redirect_to @tracker, notice: t('.notice') }
        format.json { render :show, status: :ok, location: @tracker }
      else
        format.html { render :edit }
        format.json { render json: @tracker.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /trackers/1
  # DELETE /trackers/1.json
  def destroy
    @tracker.destroy
    respond_to do |format|
      format.html { redirect_to trackers_url, notice: t('.notice') }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_tracker
      @tracker = Tracker.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def tracker_params
      params.fetch(:tracker, {})
    end
end

app/helpers/trackers_helper.rb
module TrackersHelper
end

app/views/trackers/_form.html.haml
= form_for @tracker do |f|
  - if @tracker.errors.any?
    #error_explanation
      %h2= "#{pluralize(@tracker.errors.count, "error")} prohibited this tracker from being saved:"
      %ul
        - @tracker.errors.full_messages.each do |message|
          %li= message

  .actions
    = f.submit 'Save'

app/views/trackers/edit.html.haml
%h1 Editing tracker

= render 'form'

= link_to 'Show', @tracker
\|
= link_to 'Back', trackers_path

app/views/trackers/index.html.haml
%h2= t('.title')
%h4= t('.description1')
%h4
  = t('.description2')
  %span{:style => "color:blue;font-weight:bold"}
    %a{:href => "/products"} Click Here
  ,
  = t('.description3')

%span

  %h2 Products you want! ( #{@trackers.product_to_trackers.count} )

  %table{:cellpadding => "0", :cellspacing => "0"}

    %tbody
      - @trackers.product_to_trackers.each do |item|
        %tr
          %td
            %img{:src => "/" + item.product.image, :width => 250}
        %tr
          %td= item.product.name
        %tr
          %th Collection
          %td= item.product.collection
        %tr
          %th Category
          %td= item.product.category
        %tr
          %td= link_to 'Destroy', item, method: :delete, data: { confirm: 'Are you sure?' }


  %br

app/views/trackers/show.html.haml
%p#notice= notice

%h3 Back To Products
= link_to 'Back', products_path
%h2 Products you want! ( #{@tracker.product_to_trackers.count} )

%table{:cellpadding => "0", :cellspacing => "0"}

  %tbody
    - @tracker.product_to_trackers.each do |item|
      %tr
        %td
          %img{:src => "/" + item.product.image, :width => 250}
      %tr
        %td= item.product.name
      %tr
        %th Collection
        %td= item.product.collection
      %tr
        %th Category
        %td= item.product.category
      %tr
        %td= link_to 'Destroy', item, method: :delete, data: { confirm: 'Are you sure?' }


%br