config/routes.rb
Rails.application.routes.draw do
  resources :product_to_trackers,:except => [:edit, :update, :show]
  resources :trackers, :except => [:new, :create, :edit, :update, :show, :destroy]
  resources :products, :except => [:new, :create, :edit, :update, :destroy]
  resources :comments
  devise_for :users
  resources :posts
  root 'home#home'
  get 'contact', to: 'home#contact'
  get 'products', to: 'products#index'
  get 'fourm', to: 'posts#index'
  get 'userposts', to: 'posts#display_user_posts'
  get 'tradingtracker', to: 'trackers#index'
  get 'about', to: 'about#index'
  get 'usercomments', to: 'comments#display_user_comments'
  post 'request_contact', to: 'home#request_contact'


end

app/models/product.rb
class Product < ApplicationRecord
  has_many :product_to_trackers, dependent: :destroy
  validates:name, :category,:image, :collection, presence: true
  validates :image,:name, uniqueness: true
  def self.search_by(search_term) #a model search to search by the search term inputted via the view sent via controller method
    where("LOWER(name) LIKE :search_term OR LOWER(collection) LIKE :search_term OR LOWER(category) LIKE :search_term", search_term: "%#{search_term.downcase}")
  end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :set_product, only: [:show, :edit, :update, :destroy]

  # GET /products
  # GET /products.json
  def index
    @products = Product.all
    if params[:search] #displays products related to the search term
      @search_term = params[:search]
      @products = @products.search_by(@search_term)
    end
  end

  # GET /products/1
  # GET /products/1.json
  def show
  end

  # GET /products/new
  def new
    @product = Product.new
  end

  # GET /products/1/edit
  def edit
  end

  # POST /products
  # POST /products.json
  def create
    @product = Product.new(product_params)

    respond_to do |format|
      if @product.save
        format.html { redirect_to @product, notice: t('.notice') }
        format.json { render :show, status: :created, location: @product }
      else
        format.html { render :new }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /products/1
  # PATCH/PUT /products/1.json
  def update
    respond_to do |format|
      if @product.update(product_params)
        format.html { redirect_to @product, notice: t('.notice') }
        format.json { render :show, status: :ok, location: @product }
      else
        format.html { render :edit }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /products/1
  # DELETE /products/1.json
  def destroy
    @product.destroy
    respond_to do |format|
      format.html { redirect_to products_url, notice: t('.notice') }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_product
      @product = Product.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def product_params
      params.require(:product).permit(:name, :collection, :category, :image)
    end
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/products/_form.html.haml
= form_for @product do |f|
  - if @product.errors.any?
    #error_explanation
      %h2= "#{pluralize(@product.errors.count, "error")} prohibited this product from being saved:"
      %ul
        - @product.errors.full_messages.each do |message|
          %li= message

  .field
    = f.label :name
    = f.text_field :name
  .field
    = f.label :collection
    = f.text_field :collection
  .field
    = f.label :category
    = f.text_field :category
  .field
    = f.label :image
    = f.text_field :image
  .actions
    = f.submit 'Save'

app/views/products/edit.html.haml
%h1 Editing product

= render 'form'

= link_to t('show'), @product
\|
= link_to t('back'), products_path

app/views/products/index.html.haml
%h2= t('.title')
%title= t('.title')
= form_for "",url: products_path, role: "search", method: :get do
  = text_field_tag :search, @search_term,placeholder: "Search... e.g Booster Packs"
%table{:cellpadding => "0", :cellspacing => "0"}

  %tbody

    - @products.each do |product|

      %tr
        %td
          %img{:src => product.image, :width => 300}
      %tr
        %td= product.name
      %tr
        %th Collection
        %td= product.collection
      %tr
        %th Category
        %td= product.category
      %tr
      %span
        %td= button_to t('.button'), product_to_trackers_path(product_id: product), :remote => true
      %td= link_to t('show'), product
      %td{:id => "product_#{product.id}", :style => "color:green;text-align:center;"}
%br

app/views/products/new.html.haml
%h1= t('.new')
%title= t('app_title')
= render 'form'

= link_to t('back'), products_path

app/views/products/show.html.haml
%title= t('app_title')

%table
  %tbody
    %tr
    %tr
    %td
      %p
        %b Name:
        = @product.name
      %p
        %b Collection:
        = @product.collection
      %p
        %b Category:
        = @product.category
      %p
        %b
        = link_to 'Back', products_path
      %td
        %img{:src => "/" + @product.image, :width => 500}